import Head from "next/head";
import Hero from "@/components/Hero";
import { StickyNav } from "@/components/Hero";
import History from "@/components/History";
import Climb from "@/components/Climb";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Los Angeles Mountains</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
      </Head>
      <main>
        <Hero />
        <StickyNav />
        <History />
        <Climb />
        <Footer />
      </main>
    </>
  );
}
